#!/usr/bin/env python3
"""Generate the desktop SVG from the APK's adaptive-icon layers."""
from pathlib import Path
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "android/app/src/main/res"
ANDROID = "{http://schemas.android.com/apk/res/android}"
foreground = ET.parse(RES / "drawable/ic_launcher_foreground.xml").getroot()
background = ET.parse(RES / "values/ic_launcher_background.xml").getroot()
color = background.find("color[@name='ic_launcher_background']").text
width = foreground.attrib[ANDROID + "viewportWidth"]
height = foreground.attrib[ANDROID + "viewportHeight"]
lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/sync-icon.py from the Android launcher icon. -->',
    '<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 108 108">',
    f'  <rect x="4" y="4" width="100" height="100" rx="24" fill="{color}"/>',
    f'  <svg x="4" y="4" width="100" height="100" viewBox="0 0 {width} {height}">',
]
for path in foreground:
    if path.tag != "path":
        raise SystemExit("Unsupported Android vector element; update the converter.")
    d = path.attrib[ANDROID + "pathData"]
    fill = path.attrib[ANDROID + "fillColor"]
    alpha = path.attrib.get(ANDROID + "fillAlpha", "1")
    lines.append(f'    <path d="{d}" fill="{fill}" fill-opacity="{alpha}"/>')
lines.extend(['  </svg>', '</svg>', ''])
svg = "\n".join(lines)
target = ROOT / "packaging/io.github.tymonoman.Extraspace.svg"
if sys.argv[1:] == ["--check"]:
    if target.read_text() != svg:
        raise SystemExit("Desktop icon is stale. Run python3 scripts/sync-icon.py")
elif not sys.argv[1:]:
    target.write_text(svg)
else:
    raise SystemExit("Usage: sync-icon.py [--check]")
