#!/usr/bin/env python3
"""Generate Android palettes and GTK accents from the shared product palette."""
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
theme = json.loads((ROOT / "design/theme.json").read_text())
outputs = {}
for mode, qualifier in [("light", "values"), ("dark", "values-night")]:
    colors = dict(theme[mode], accent=theme["accent"], accent_text=theme["accent_text"])
    outputs[ROOT / f"android/app/src/main/res/{qualifier}/colors.xml"] = (
        '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/sync-theme.py. -->\n<resources>\n' +
        ''.join(f'    <color name="xs_{name}">{value}</color>\n' for name, value in colors.items()) + '</resources>\n')
outputs[ROOT / "crates/xs-ui/src/theme.css"] = f'''/* Generated by scripts/sync-theme.py. Native Adwaita supplies light/dark surfaces. */
@define-color accent_bg_color {theme['accent']};
@define-color accent_fg_color {theme['accent_text']};
@define-color accent_color {theme['accent']};
.suggested-action {{ background-color: {theme['accent']}; color: {theme['accent_text']}; }}
switch:checked {{ background-color: {theme['accent']}; }}
'''
for path, content in outputs.items():
    if sys.argv[1:] == ["--check"]:
        if not path.exists() or path.read_text() != content:
            sys.exit("Shared theme is stale. Run python3 scripts/sync-theme.py")
    elif not sys.argv[1:]:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    else: sys.exit("Usage: sync-theme.py [--check]")
